### ISSUE TITLE
Question about gesture recognition 

### ISSUE THREAD

**Issue by wrfokokokwrf** [acconeer/acconeer-a121-gesture-control#1]
How do I burn a python program of acconeer-a121-gesture-control to the chip of A111.
Thank you.

**Comment by AlbTommy** [comment]
Hi,

Note, this example only works with a121 and not a111.

By the 'burn', do you mean compiling C-code for an embedded application? If so, we do not have any support for that as of today. You can try generating C code using Keras2C for instance(https://github.com/f0uriest/keras2c), and then compile it for your target device.

Let me know if you have any further questions.
