### ISSUE TITLE
Error exucting the jupyter notebook model_development.ipynb

### ISSUE THREAD

**Issue by paul-dls** [acconeer/acconeer-a121-gesture-control#2]
## Describe the bug
the Jupyter notebbok in acconeer-a121-gesture-control-main\model_development.ipynb doesn't work 
The code in Gesture detection crashes in line 3

## Screenshots/Video
![Screenshot 2023-04-11 134314](https://user-images.githubusercontent.com/80622713/231153544-ab699755-8601-41f9-8e88-55c3f53adca5.png)

## To Reproduce
clone the github repo and lunch the jupyter notebook 

## Config
 - OS: windows 11 
 - python : v3.9.13

## quick fix : 
replace line 71 in util.py
`    vels, _ = get_approx_fft_vels(sensor_config)`
by 
`    vels, _ = get_approx_fft_vels(None,sensor_config)`

**Comment by AndersBuhl** [comment]
Hi,

Thanks for reporting this. It should be fixed [now](https://github.com/acconeer/acconeer-a121-gesture-control/commit/e70494afc08fbe6ef08119bd022eb55d8a4246a8)!

BR
Anders
